const Hospital = require('../models/Hospital');
const connectDB = require('../config/db');

const sknHospitals = [
  {
    name: 'Sanyukt Zila Chikitsalaya (District Combined Hospital)',
    email: 'contact.skn.districthospital@caresync.org',
    phone: '+91 5547 226102',
    emergencyPhone: '+91 94508 22108',
    address: 'Near Collectorate, NH-27, Khalilabad, Sant Kabir Nagar',
    city: 'Khalilabad',
    state: 'Uttar Pradesh',
    pincode: '272175',
    location: {
      type: 'Point',
      coordinates: [83.0560, 26.7780], // [lng, lat]
    },
    hospitalType: 'Government District Hospital',
    verificationStatus: 'VERIFIED',
    emergencyAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: true,
    pharmacyAvailable: true,
    diagnosticAvailable: true,
    operatingHours: '24/7 Emergency & In-Patient Services',
    departments: ['Emergency Medicine', 'General Surgery', 'Cardiology', 'Orthopedics', 'Pediatrics', 'Obstetrics & Gynecology'],
    capacitySummary: {
      general: { total: 120, available: 38 },
      icu: { total: 15, available: 4 },
      emergency: { total: 12, available: 3 },
    },
    rating: 4.5,
    totalReviews: 340,
    lastStatusUpdate: new Date(Date.now() - 12 * 60 * 1000),
  },
  {
    name: 'Katai Bazar Community Health Center (CHC Katai Bazar)',
    email: 'chc.kataibazar@caresync.org',
    phone: '+91 5547 227411',
    emergencyPhone: '+91 94508 22102',
    address: 'Katai Bazar, Main Market Road, Khalilabad, Sant Kabir Nagar',
    city: 'Khalilabad',
    state: 'Uttar Pradesh',
    pincode: '272175',
    location: {
      type: 'Point',
      coordinates: [83.0640, 26.7725],
    },
    hospitalType: 'Community Health Center',
    verificationStatus: 'VERIFIED',
    emergencyAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: false,
    pharmacyAvailable: true,
    diagnosticAvailable: true,
    operatingHours: '24/7 Primary Emergency & Trauma',
    departments: ['Emergency Medicine', 'General Medicine', 'Pediatrics', 'Obstetrics'],
    capacitySummary: {
      general: { total: 40, available: 18 },
      icu: { total: 4, available: 1 },
      emergency: { total: 6, available: 2 },
    },
    rating: 4.4,
    totalReviews: 185,
    lastStatusUpdate: new Date(Date.now() - 8 * 60 * 1000),
  },
  {
    name: 'Surya Super-Specialty Hospital & Trauma Centre',
    email: 'info.suryahospital.skn@caresync.org',
    phone: '+91 5547 229880',
    emergencyPhone: '+91 98390 44550',
    address: 'Bypass Road, Near Katai Bazar Mor, Khalilabad, Sant Kabir Nagar',
    city: 'Khalilabad',
    state: 'Uttar Pradesh',
    pincode: '272175',
    location: {
      type: 'Point',
      coordinates: [83.0610, 26.7820],
    },
    hospitalType: 'Super-Specialty Hospital',
    verificationStatus: 'VERIFIED',
    emergencyAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: true,
    pharmacyAvailable: true,
    diagnosticAvailable: true,
    operatingHours: '24/7 Critical Care & ICU',
    departments: ['Emergency Medicine', 'Cardiology', 'Orthopedics', 'Neurology', 'Intensive Care'],
    capacitySummary: {
      general: { total: 65, available: 26 },
      icu: { total: 14, available: 4 },
      emergency: { total: 8, available: 3 },
    },
    rating: 4.7,
    totalReviews: 420,
    lastStatusUpdate: new Date(Date.now() - 15 * 60 * 1000),
  },
  {
    name: 'LifeLine Multi-Specialty Hospital & Heart Care',
    email: 'care.lifeline.khalilabad@caresync.org',
    phone: '+91 5547 225330',
    emergencyPhone: '+91 99180 33440',
    address: 'Mukhlishpur Road, Near Gandhi Chowk, Khalilabad, Sant Kabir Nagar',
    city: 'Khalilabad',
    state: 'Uttar Pradesh',
    pincode: '272175',
    location: {
      type: 'Point',
      coordinates: [83.0510, 26.7710],
    },
    hospitalType: 'Multi-Specialty Hospital',
    verificationStatus: 'VERIFIED',
    emergencyAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: true,
    pharmacyAvailable: true,
    diagnosticAvailable: true,
    operatingHours: '24/7 Cardiac & Emergency Care',
    departments: ['Cardiology', 'Emergency Medicine', 'General Surgery', 'Orthopedics'],
    capacitySummary: {
      general: { total: 50, available: 19 },
      icu: { total: 10, available: 3 },
      emergency: { total: 6, available: 2 },
    },
    rating: 4.6,
    totalReviews: 290,
    lastStatusUpdate: new Date(Date.now() - 22 * 60 * 1000),
  },
  {
    name: 'Apex Trauma Centre & Critical Care',
    email: 'help.apex.skn@caresync.org',
    phone: '+91 5547 228990',
    emergencyPhone: '+91 97950 11220',
    address: 'Bankata Overbridge Road, Khalilabad, Sant Kabir Nagar',
    city: 'Khalilabad',
    state: 'Uttar Pradesh',
    pincode: '272175',
    location: {
      type: 'Point',
      coordinates: [83.0720, 26.7690],
    },
    hospitalType: 'Trauma & Critical Care',
    verificationStatus: 'VERIFIED',
    emergencyAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: false,
    pharmacyAvailable: true,
    diagnosticAvailable: true,
    operatingHours: '24/7 Trauma Services',
    departments: ['Emergency Medicine', 'Orthopedics', 'General Surgery', 'Pulmonology'],
    capacitySummary: {
      general: { total: 55, available: 21 },
      icu: { total: 8, available: 2 },
      emergency: { total: 8, available: 3 },
    },
    rating: 4.5,
    totalReviews: 210,
    lastStatusUpdate: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    name: 'Sanjeevani Care Hospital & Maternity Center',
    email: 'info.sanjeevani.khalilabad@caresync.org',
    phone: '+91 5547 224410',
    emergencyPhone: '+91 94150 99880',
    address: 'Mehdawal Road, Near Railway Crossing, Khalilabad, Sant Kabir Nagar',
    city: 'Khalilabad',
    state: 'Uttar Pradesh',
    pincode: '272175',
    location: {
      type: 'Point',
      coordinates: [83.0580, 26.7860],
    },
    hospitalType: 'Multi-Specialty Hospital',
    verificationStatus: 'VERIFIED',
    emergencyAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: false,
    pharmacyAvailable: true,
    diagnosticAvailable: true,
    operatingHours: '24/7 Emergency & Maternity Care',
    departments: ['Obstetrics & Gynecology', 'Pediatrics', 'Emergency Medicine', 'General Medicine'],
    capacitySummary: {
      general: { total: 40, available: 15 },
      icu: { total: 6, available: 2 },
      emergency: { total: 5, available: 2 },
    },
    rating: 4.4,
    totalReviews: 160,
    lastStatusUpdate: new Date(Date.now() - 35 * 60 * 1000),
  },
  {
    name: 'Maharshi Vashishtha Autonomous State Medical College Hospital',
    email: 'contact.medicalcollege.basti@caresync.org',
    phone: '+91 5542 284100',
    emergencyPhone: '+91 94500 10810',
    address: 'Rampur, NH-27, Basti (Sant Kabir Nagar border)',
    city: 'Basti',
    state: 'Uttar Pradesh',
    pincode: '272002',
    location: {
      type: 'Point',
      coordinates: [82.7820, 26.7950],
    },
    hospitalType: 'Government Medical College Hospital',
    verificationStatus: 'VERIFIED',
    emergencyAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: true,
    pharmacyAvailable: true,
    diagnosticAvailable: true,
    operatingHours: '24/7 Emergency & Tertiary Care',
    departments: ['Emergency Medicine', 'General Surgery', 'Cardiology', 'Neurology', 'Orthopedics', 'Pediatrics', 'Nephrology'],
    capacitySummary: {
      general: { total: 350, available: 75 },
      icu: { total: 30, available: 6 },
      emergency: { total: 20, available: 4 },
    },
    rating: 4.6,
    totalReviews: 540,
    lastStatusUpdate: new Date(Date.now() - 5 * 60 * 1000),
  },
  {
    name: 'District Hospital Basti (Shri Shiv Prasad Gupta Chikitsalaya)',
    email: 'districthospital.basti@caresync.org',
    phone: '+91 5542 282102',
    emergencyPhone: '+91 94500 10210',
    address: 'Company Bagh, Malviya Road, Basti',
    city: 'Basti',
    state: 'Uttar Pradesh',
    pincode: '272001',
    location: {
      type: 'Point',
      coordinates: [82.7480, 26.8010],
    },
    hospitalType: 'Government District Hospital',
    verificationStatus: 'VERIFIED',
    emergencyAvailable: true,
    ambulanceAvailable: true,
    bloodBankAvailable: true,
    pharmacyAvailable: true,
    diagnosticAvailable: true,
    operatingHours: '24/7 Emergency & Trauma',
    departments: ['Emergency Medicine', 'General Surgery', 'Orthopedics', 'Pediatrics', 'General Medicine'],
    capacitySummary: {
      general: { total: 200, available: 48 },
      icu: { total: 18, available: 4 },
      emergency: { total: 15, available: 3 },
    },
    rating: 4.4,
    totalReviews: 380,
    lastStatusUpdate: new Date(Date.now() - 18 * 60 * 1000),
  }
];

const seedSKN = async () => {
  try {
    await connectDB();
    console.log('Connected to DB');

    for (const h of sknHospitals) {
      await Hospital.findOneAndUpdate(
        { name: h.name },
        h,
        { upsert: true, new: true }
      );
      console.log('Upserted:', h.name);
    }

    console.log('Sant Kabir Nagar / Khalilabad hospitals seeded successfully!');
    process.exit(0);
  } catch (err) {
    console.error('Seeding error:', err);
    process.exit(1);
  }
};

seedSKN();
